services:
  app:
    build: .
    ports:
      - "5005:8080"  # Mapeia a porta 80 do container para a porta 5005 do host
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  # Configura o ambiente como Produção, se necessário
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: daily_feelings
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    driver: local